### ISSUE TITLE
Various edits

### ISSUE THREAD

**Issue by alzulas** [InfoSec-Unlocked/website#15]
- CFP Review Program should also be available on the future speakers page
- "InfoSec Unlocked 501(c)(3) is a non-profit organization " should be "InfoSec Unlocked is a 501(c)(3) non-profit organization "
- Mission statement text seems incomplete?
- Organization list seems incomplete?
- Diversity and Inclusion takes me to a black hole. 

Everything else looks good. Like the new form. Keep it up.

**Comment by t-walker** [comment]
got these
