### ISSUE TITLE
Change "Code of Conducts" to "Codes of Conduct"

### ISSUE THREAD

**Issue by sushidude1227** [InfoSec-Unlocked/website#26]
Some pages mention "Code of Conducts," but since we are talking about multiple codes, the term should be "Codes of Conduct."

This is at least on the Diversity & Inclusion page.

**Comment by t-walker** [comment]
Addressed in #29

**Comment by sushidude1227** [comment]
This was closed but has not been fully addressed. Some pages say "Code of Conducts" multiple times - so all instances need to be fixed, not just the first one. e.g. Diversity.js. Doing aomething like a case-insensitive grep of "code of conducts"  will help to root out many/all of the other instances.

**Comment by t-walker** [comment]
I did a scan through and I think I got all of them.
